### ISSUE TITLE
UTFGrid support

### ISSUE THREAD

**Issue by yjacolin** [mapserver/docs#131]
http://mapserver.org/development/rfc/ms-rfc-93.html (code contribution in https://github.com/mapserver/mapserver/pull/4765)

**Comment by havatv** [comment]
I can start.  Will add the new LAYER parameters and the new formatoption in OUTPUTFORMAT

**Comment by dmorissette** [comment]
Thank you guys for looking into this.

**Comment by dmorissette** [comment]
Guys, please have a look at this branch which contains some docs already:
https://github.com/fdesj/docs/commit/f2bcfcc7e42a8b9f1bd9d389bb7755f3400ee7a8

they were submitted in pull request #50 but we closed it without merging because it needed a bit of work, and then never got back to it. Apologies, that is in large part my fault.

**Comment by havatv** [comment]
I guess I was too fast on this one @dmorissette, so some double work here...  I will try to update the docs using pull request #50.

**Comment by havatv** [comment]
I close this one now.  Please reopen if something more needs to be done.
